### ISSUE TITLE
Issues with powerdot clock

### ISSUE THREAD

**Issue by strangedata** [agrahn/animate#1]
Hi,

I'm trying to use animate with powerdot, while also using powerdot's clock option. The problem is that the clock isn't showing up, just a blueish rectangle where it should come up.

On 2011 animate received a fix to deal with powerdot's clock properly, as stated on this post:
https://www.freelists.org/post/powerdot/Problem-using-clock-with-animate-package,1

Looking at animate.sty revision I see that the fix was introduced in 2011, but it was removed some time later. My current version (Jan 2017) doesn't show the modifications.

I also tried setting pd clockformat and clockrefresh rate as suggested to no avail.

Here's a minimal example:
```
\documentclass[
                                style=simple,
                                paper=screen,
                                mode=present,
                                fleqn,
                                orient=landscape,
                                clock]{powerdot}

\usepackage{animate}

\pdsetup{
        clockformat=HH:MM,
        clockrefresh=60000
}

\pddefinetemplate[slide]{slide}{
 textpos={.20\slidewidth,.75\slideheight},
 textwidth=.75\slidewidth,
 titlepos={.15\slidewidth,.85\slideheight},
 tocpos={.015\slidewidth,.75\slideheight},
 clockpos={.23\slidewidth,.08\slideheight},
}{}

\begin{document}

\begin{slide}{test}
        \begin{itemize}
                \item 1
                \item 2
        \end{itemize}
\end{slide}

\begin{slide}{animate slide}
\centering\animategraphics{1}{fundo-slides}{1}{1}
\end{slide}

\end{document}
```

Thanks!

**Comment by agrahn** [comment]
I wrote a package which replaces the Powerdot clock and maintains compatibility with `animate`: 

[`pdclock.sty`](https://gist.github.com/agrahn/bb6e6c6911f8cb919a64d9b7ba3daf59)

**Comment by agrahn** [comment]
`pdclock.sty` is not required anymore as it was incorporated into Powerdot.
