### ISSUE TITLE
Documentation: workaround for limited overlay support

### ISSUE THREAD

**Issue by javidcf** [agrahn/animate#2]
This is probably not the best place to submit this, but I did not know how else to contact the author of the package. I am using `animate` for a Beamer presentation and it is fantastic. As acknowledged in the documentation, though, there is currently no support for overlays (multi-page slides), which means that: a) animations in different pages of a frame work independently (so advancing a page stops a playing animation) and b) animations do not respect overlay specifications, and they are visible always since the first page of the frame. The documentation includes a reference to [a TeX.SE post](https://tex.stackexchange.com/questions/384890/beamer-animate-package-and-overlay) to overcome the first problem, but not the second one. After trying a few things, I found out that the second problem can actually be avoided quite simply with `tikz`, which provides full overlay support:

```
\documentclass[11pt]{beamer}
\usepackage[draft]{animate}
\usepackage{tikz}
\begin{document}
\begin{frame}{A slide}
Some text first.
\begin{tikzpicture}
\node<2-> {\animategraphics[width=3cm]{10}{anim/frame_}{1}{10}};
\end{tikzpicture}
\end{frame}
\end{document}
```

I don't know if this works in all cases, and it has its caveats, like the size of the animation is not taken into account (this is just how TikZ overlays work, I found it can in turn be worked around by creating an invisible TikZ node on every page without animation of a similar size), but I thought you might consider adding a note in the documentation, since it took me a while to find a solution almost by chance.

**Comment by agrahn** [comment]
Thank you for commenting.

This approach doesn't reserve space for the animation on slides where it is not supposed to appear. A similar effect could be achieved more easily by just placing the animation into an `\only<2->{...}`. Did you consider this option?

**Comment by javidcf** [comment]
@agrahn Yes, you are right, that also works and it is far simpler :) I used TikZ to add also empty nodes on the slides without animation to reserve the space where needed (still unnecessary to use TikZ, I know, but I was using it already and I am actually more fluent with it than LaTeX...). Far from ideal, though, it took me a while of trial and error to find just the exact placeholder size so everything stays perfectly still between pages... Probably the easiest thing would have been a permanent fixed-size `\makebox` and then `\only` with a `textblock` (from `textpos` package) on top...

Anyways thanks for your answer and for your work in `animate`.

**Comment by agrahn** [comment]
Just another option, if you want to reserve space on "silent" slides. There is the user-command `\alt<...>{}{}`. We could use it as follows (note the `draft` option in the alternative clause):

```latex
\alt<2->{
  \animategraphics[width=3cm]{10}{anim/frame_}{1}{10}
}{
  \phantom{\animategraphics[draft,width=3cm]{10}{anim/frame_}{1}{10}}
}
```
Together with "connecting" related animations, as suggested on TeX.SX:

```latex
\alt<2->{
  \putBeforeAnim{myAnim}%
  \animategraphics[label=myAnim_\thepage,width=3cm]{10}{anim/frame_}{1}{10}%
  \putAfterAnim{myAnim}
}{
  \phantom{\animategraphics[draft,width=3cm]{10}{anim/frame_}{1}{10}}
}
```

**Comment by agrahn** [comment]
I have made an edit to the TeX.SX topic which incorporates this idea. Do you think we can close the issue?

**Comment by javidcf** [comment]
@agrahn Absolutely, I'm not even very sure it should have been an "issue" as such in the first place!
Thanks for the support.
